# default
spring:
  profiles:
    active: local
    group:
      local:  # local, common profile을 그룹지어 함께 어플리케이션 구동    
        - inmemory
      prod:   # prod, common profile을 그룹지어 함께 어플리케이션 구동  
        - mongo

---
spring:
  config:
    activate:
      on-profile: common   # application-common.yml 과 동일한 역할

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod

mongo:
  connectionString: mongodb://root:rms_was@mongo:27017/
  databaseName: rms
  materialCollectionName: materials
