recipe:
  recipes:
    - id: common_coffee_1
      name: coffee
      ingredients:
        - amount: 20
          material:
            id: brazil_coffee_bean_1
        - amount: 10
          material:
            id: ice_1
    - id: common_latte_1
      name: latte
      ingredients:
        - material:
            id: brazil_coffee_bean_1
          amount: 20
        - amount: 10
          material:
            id: ice_1
        - amount: 175
          material:
            id: milk_1
    - id: common_vanilla_latte_1
      name: vanilla_latte
      ingredients:
        - amount: 20
          material:
            id: brazil_coffee_bean_1
        - amount: 10
          material:
            id: ice_1
        - amount: 170
          material:
            id: milk_1
        - amount: 35
          material:
            id: vanilla_syrup
    - id: common_caramel_macchiato_1
      name: caramel_macchiato
      ingredients:
        - amount: 20
          material:
            id: brazil_coffee_bean_1
        - amount: 10
          material:
            id: ice_1
        - amount: 150
          material:
            id: milk_1
        - amount: 35
          material:
            id: caramel_syrup
material-price:
  priceMap:
    brazil_coffee_bean_1: 26
    ice_1: 30
    milk_1: 1.68
    vanilla_syrup: 13.96
    caramel_syrup: 16