name: CI

on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  docker-compose-scp:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v0.1.4
      - name: copy file via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: "docker-compose.yml"
          target: ~/rms-was/docker-compose.yml
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test And Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: |
            test
            build
          gradle-version: 7.5.1
