name: CI

on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  ssh-test:
    runs-on: ubuntu-latest
    name: ssh-test
    steps:
      - name: SSH Command
        # You may pin to the exact commit or the version.
        # uses: D3rHase/ssh-command-action@51ec3cec93e9557d7a5289c1e31a4a28185e5200
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          # hostname / IP of the server
          host: ${{ secrets.SERVER_HOST }}
          # ssh port of the server
          port: ${{ secrets.SERVER_SSH_PORT }} # optional, default is 22
          # user of the server
          user: ${{ secrets.SERVER_SSH_USER }}
          # private ssh key registered on the server
          private_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          # command to be executed
          command: echo 'Hello world' >> ~/ssh_succeed.txt # optional, default is echo 'Hello world'
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test And Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: |
            test
            build
          gradle-version: 7.5.1